[general]
enable_bucket = true                        # 是否使用Aspect Ratio Bucketing

[[datasets]]
resolution = 512                            # 训练分辨率
batch_size = 4                              # 批次大小

  [[datasets.subsets]]
  image_dir = '/mnt/c/Users/31760/Desktop/lora_test/lion/50_body'                     # 指定包含训练图像的文件夹
  class_tokens = 'LiNusSg'                # 指定标识符类
  num_repeats = 100                          # 训练图像的重复次数

  # 以下仅在使用正则化图像时进行描述。不使用则删除
  #[[datasets.subsets]]
  #is_reg = true
  #image_dir = '/mnt/c/Users/31760/Desktop/lora_test/lion/50_face'                      # 指定包含正则化图像的文件夹
  #class_tokens = 'girl'                     # 指定class
  #num_repeats = 1                           # 正则化图像的重复次数，基本上1就可以了